wandb_version: 1

batch_size:
  value: 256
cell_type:
  value: GRU
decoder_layers:
  value: 4
dropout:
  value: 0.4
encoder_layers:
  value: 2
hidden_layer_size:
  value: 512
input_embedding:
  value: 256
learning_rate:
  value: 0.001
