wandb_version: 1

batch_size:
  value: 128
cell_type:
  value: RNN
decoder_layers:
  value: 3
dropout:
  value: 0.3
encoder_layers:
  value: 2
hidden_layer_size:
  value: 512
input_embedding:
  value: 256
learning_rate:
  value: 0.0001
