wandb_version: 1

batch_size:
  value: 128
cell_type:
  value: GRU
decoder_layers:
  value: 2
dropout:
  value: 0.2
encoder_layers:
  value: 1
hidden_layer_size:
  value: 64
input_embedding:
  value: 256
learning_rate:
  value: 0.001
