wandb_version: 1

batch_size:
  value: 128
cell_type:
  value: LSTM
decoder_layers:
  value: 4
dropout:
  value: 0.2
encoder_layers:
  value: 3
hidden_layer_size:
  value: 512
input_embedding:
  value: 512
learning_rate:
  value: 0.001
