wandb_version: 1

batch_size:
  value: 256
cell_type:
  value: RNN
decoder_layers:
  value: 2
dropout:
  value: 0.3
encoder_layers:
  value: 4
hidden_layer_size:
  value: 512
input_embedding:
  value: 128
learning_rate:
  value: 0.0001
