wandb_version: 1

batch_size:
  value: 64
cell_type:
  value: RNN
decoder_layers:
  value: 4
dropout:
  value: 0.2
encoder_layers:
  value: 4
hidden_layer_size:
  value: 512
input_embedding:
  value: 512
learning_rate:
  value: 0.0001
