wandb_version: 1

batch_size:
  value: 64
cell_type:
  value: LSTM
decoder_layers:
  value: 2
dropout:
  value: 0.2
encoder_layers:
  value: 1
hidden_layer_size:
  value: 64
input_embedding:
  value: 64
learning_rate:
  value: 0.001
