wandb_version: 1

batch_size:
  value: 64
cell_type:
  value: LSTM
decoder_layers:
  value: 4
dropout:
  value: 0.1
encoder_layers:
  value: 1
hidden_layer_size:
  value: 64
input_embedding:
  value: 128
learning_rate:
  value: 0.001
