_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.16
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.16
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 256
beam_size:
    value: 1
cell_type:
    value: LSTM
decoder_bidirectional:
    value: false
decoder_layers:
    value: 4
dropout:
    value: 0.3
encoder_bidirectional:
    value: true
encoder_layers:
    value: 3
hidden_layer_size:
    value: 512
input_embedding:
    value: 64
learning_rate:
    value: 0.001
num_epochs:
    value: 10
use_attention:
    value: false
wandb_entity:
    value: jay_gupta-indian-institute-of-technology-madras
wandb_project:
    value: Transliteration
