wandb_version: 1

batch_size:
  value: 256
cell_type:
  value: LSTM
decoder_layers:
  value: 1
dropout:
  value: 0.3
encoder_layers:
  value: 3
hidden_layer_size:
  value: 512
input_embedding:
  value: 128
learning_rate:
  value: 0.001
