wandb_version: 1

batch_size:
  value: 128
cell_type:
  value: LSTM
decoder_layers:
  value: 1
dropout:
  value: 0.4
encoder_layers:
  value: 4
hidden_layer_size:
  value: 512
input_embedding:
  value: 64
learning_rate:
  value: 0.001
