wandb_version: 1

batch_size:
  value: 64
cell_type:
  value: GRU
decoder_layers:
  value: 3
dropout:
  value: 0.1
encoder_layers:
  value: 1
hidden_layer_size:
  value: 128
input_embedding:
  value: 64
learning_rate:
  value: 0.0001
