wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.16
    cli_version: 0.19.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1747621541
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 14
      - 16
      - 23
      - 37
      4: 3.10.16
      5: 0.19.11
      8:
      - 5
      13: linux-x86_64
wandb_project:
  desc: null
  value: Transliteration
wandb_entity:
  desc: null
  value: jay_gupta-indian-institute-of-technology-madras
num_epochs:
  desc: null
  value: 10
batch_size:
  desc: null
  value: 128
input_embedding:
  desc: null
  value: 512
encoder_layers:
  desc: null
  value: 3
decoder_layers:
  desc: null
  value: 4
learning_rate:
  desc: null
  value: 0.001
hidden_layer_size:
  desc: null
  value: 512
cell_type:
  desc: null
  value: LSTM
dropout:
  desc: null
  value: 0.3
encoder_bidirectional:
  desc: null
  value: true
decoder_bidirectional:
  desc: null
  value: false
use_attention:
  desc: null
  value: false
beam_size:
  desc: null
  value: 1
